### ISSUE TITLE
Does not work in Chrome?

### ISSUE THREAD

**Issue by koliada** [tholman/overscroll#2]
Hey, I was just walking by, but I've tried it recently [here](http://tholman.com/overscroll/) and seems that it doesn't work for me (Chrome Version 40.0.2214.94 m), so I decided to report.
Thanks.

**Comment by tholman** [comment]
Definitely works on that version for me. Could be that you're on windows, which doesn't do the overscroll, like mac's do... or you have it turned off :)

**Comment by koliada** [comment]
You're right! Haven't noticed that it is all about Mac.
