### ISSUE TITLE
Broken in Google Chrome 42 / Canary

### ISSUE THREAD

**Issue by Martin-Pitt** [tholman/overscroll#4]
It's not a fault of the library, but Chrome are changing overscroll functionality a lot, by accident they broke the way that 'scroll' event returns the scroll positions in overscroll.

I have reported the regression at https://code.google.com/p/chromium/issues/detail?id=458060
If you could pipe in maybe that would help, being able to create overscroll UIs would be really superb as web dev. This library is neat as it works both mobile and desktop, even if it's OSX specific.

**Comment by tholman** [comment]
Urgh, thats no good. I mean, if its something that they deploy, so be it, totally makes sense too :)

Going to close this one as wontfix on my end, but hopefully they implementing scrolling the similar way on their end :)
